variable "vms" {
  description = "List of VM configurations."
  type = list(object({
    accept_plan                          = optional(bool, false)
    admin_password                       = string
    admin_username                       = string
    allocation_method                    = optional(string, "Static")
    allow_extension_operations           = optional(bool, true)
    asg_id                               = optional(string, null)
    asg_name                             = optional(string, null)
    availability_set_id                  = optional(string)
    availability_zone                    = optional(string, "random")
    boot_diagnostics_storage_account_uri = optional(string, null)
    computer_name                        = optional(string)
    create_asg                           = optional(bool, true)
    custom_data                          = optional(string)
    custom_source_image_id               = optional(string, null)
    enable_accelerated_networking        = optional(bool, false)
    enable_automatic_updates             = optional(bool, true)
    enable_encryption_at_host            = optional(bool, false)
    identity_ids                         = optional(list(string))
    identity_type                        = optional(string)
    license_type                         = optional(string)
    location                             = string
    name                                 = string
    nic_ipconfig_name                    = optional(string)
    nic_name                             = optional(string, null)
    os_disk_caching                      = optional(string, "ReadWrite")
    os_disk_name                         = optional(string)
    os_disk_size_gb                      = optional(number, 128)
    os_disk_type                         = optional(string, "StandardSSD_LRS")
    patch_mode                           = optional(string, "AutomaticByOS")
    pip_custom_dns_label                 = optional(string)
    pip_name                             = optional(string)
    provision_vm_agent                   = optional(bool, true)
    public_ip_sku                        = optional(string, null)
    rg_name                              = string
    source_image_reference               = optional(map(string))
    spot_instance                        = optional(bool, false)
    spot_instance_eviction_policy        = optional(string)
    spot_instance_max_bid_price          = optional(string)
    static_private_ip                    = optional(string)
    subnet_id                            = string
    tags                                 = map(string)
    timezone                             = optional(string)
    ultra_ssd_enabled                    = optional(bool, false)
    use_custom_image                     = optional(bool, false)
    use_custom_image_with_plan           = optional(bool, false)
    use_simple_image                     = optional(bool, true)
    use_simple_image_with_plan           = optional(bool, false)
    vm_os_id                             = optional(string, "")
    vm_os_offer                          = optional(string)
    vm_os_publisher                      = optional(string)
    vm_os_simple                         = optional(string)
    vm_os_sku                            = optional(string)
    vm_os_version                        = optional(string)
    vm_size                              = string
  }))
  default = []
}
